ci:
  skip:
    - cargo-check
    - cargo-clippy

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        args: ["--cache-location=.prettier_cache/cache"]
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        args: ["--option", "array_auto_collapse=false"]
      - id: taplo-lint
        args: ["--no-schema"]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==25.1.0"]
      - id: blackdoc-autoupdate-black
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args:
          - "--extra-keys=metadata.kernelspec"
          - "metadata.language_info.version"
  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
        exclude: ".*\\.ipynb$"
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: rust
        types: [rust]
        pass_filenames: false # This makes it a lot faster
      - id: cargo-check
        name: cargo check
        entry: cargo check --profile test --
        language: rust
        types: [rust]
        pass_filenames: false # This makes it a lot faster
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --tests -- -D warnings
        language: rust
        types: [rust]
        pass_filenames: false # This makes it a lot faster
