[package]
name = "grid-weights"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "grid_weights"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.1"
