name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-ci-trigger:
    name: detect ci trigger
    runs-on: ubuntu-latest
    if: |
      github.repository == 'keewis/grid-weights'
      && (github.event_name == 'push' || github.event_name == 'pull_request')
    outputs:
      triggered: ${{ steps.detect-trigger.outputs.trigger-found }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: xarray-contrib/ci-trigger@v1
        id: detect-trigger
        with:
          keyword: "[skip-ci]"

  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    needs: detect-ci-trigger
    if: needs.detect-ci-trigger.outputs.triggered == 'false'

    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
        python-version: ["3.10", "3.12", "3.13"]

    env:
      FORCE_COLOR: 3

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: rust-tests
          environment-file: ci/requirements/environment-rust.yaml
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-rust-py${{ matrix.python-version }}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Create rust cache
        uses: Swatinem/rust-cache@v2

      - name: Help finding installed libraries
        run: |
          pushd $CONDA_PREFIX
          if [[ ${{ runner.os }} == "Windows" ]]; then
            export PKG_CONFIG_PATH="$(readlink -f Library/lib/pkgconfig)"
            export LD_LIBRARY_PATH="$(readlink -f Library/lib)"
          else
            export PKG_CONFIG_PATH="$(readlink -f lib/pkgconfig)"
            export LD_LIBRARY_PATH="$(readlink -f lib)"
          fi
          popd

          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PYO3_PYTHON=$(which python)" >> $GITHUB_ENV

      - name: Help the linker on macos
        if: runner.os == 'MacOS'
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"

          mkdir -p target/debug/deps
          ln -s $CONDA_PREFIX/lib/*.dylib target/debug/deps/

          pkg-config --libs --cflags proj 'proj >= 9.4.0'
          pkgconf --libs --cflags proj 'proj >= 9.4.0'

      - name: Clean up pkg-config
        if: runner.os == 'Windows'
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"

          # remove dependency paths
          sed -i '/Requires.private:/d' $PKG_CONFIG_PATH/*.pc

          # check that this actually works
          pkg-config --libs --cflags proj 'proj >= 9.4.0'

      - name: Run tests
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"
          export PYO3_PYTHON="${{env.PYO3_PYTHON}}"

          cargo build --tests --keep-going
          cargo test --no-fail-fast

  lint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: 3

    strategy:
      matrix:
        python-version: ["3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: rust-tests
          environment-file: ci/requirements/environment-rust.yaml
          cache-environment: true
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-rust-linting-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}"
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Create rust cache
        uses: Swatinem/rust-cache@v2

      - name: Help finding installed libraries
        run: |
          pushd $CONDA_PREFIX
          if [[ ${{ runner.os }} == "Windows" ]]; then
            export PKG_CONFIG_PATH="$(readlink -f Library/lib/pkgconfig)"
            export LD_LIBRARY_PATH="$(readlink -f Library/lib)"
          else
            export PKG_CONFIG_PATH="$(readlink -f lib/pkgconfig)"
            export LD_LIBRARY_PATH="$(readlink -f lib)"
          fi
          popd

          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PYO3_PYTHON=$(which python)" >> $GITHUB_ENV

      - name: Help the linker on macos
        if: runner.os == 'MacOS'
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"

          mkdir -p target/debug/deps
          ln -s $CONDA_PREFIX/lib/*.dylib target/debug/deps/

          pkg-config --libs --cflags proj 'proj >= 9.4.0'
          pkgconf --libs --cflags proj 'proj >= 9.4.0'

      - name: Clean up pkg-config on windows
        if: runner.os == 'Windows'
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"

          # remove dependency paths
          sed -i '/Requires.private:/d' $PKG_CONFIG_PATH/*.pc

          # check that this actually works
          pkg-config --libs --cflags proj 'proj >= 9.4.0'

      - name: Check pkg-config on linux
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"
          pkg-config --libs --cflags proj 'proj >= 9.4.0'

      - name: Cargo clippy
        run: |
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"
          export PYO3_PYTHON="${{env.PYO3_PYTHON}}"

          cargo clippy --tests -- -D warnings
